DELIMITER ;

CREATE TABLE IF NOT EXISTS `mitarbeiter` (
  `id` varchar(36) NOT NULL,
  `personal_nummer` varchar(20) DEFAULT '',
  `kurzbezeichnung` varchar(8) NOT NULL,
  `titel` varchar(255) NOT NULL,
  `anreden` varchar(255) NOT NULL,
  `vorname` varchar(255) NOT NULL,
  `nachname` varchar(255) NOT NULL,
  `bemerkungen` varchar(255) NOT NULL,
  `stellenbezeichnung` varchar(255) DEFAULT '----',
  `anstellung` date NOT NULL,
  `entlassung` date DEFAULT NULL,
  `geburtstag` date DEFAULT NULL,
  `urlaubstage` int(11) DEFAULT 0,
  `strasse` varchar(255) NOT NULL DEFAULT '',
  `plz` varchar(10) NOT NULL DEFAULT '',
  `ort` varchar(255) NOT NULL DEFAULT '',
  `ortsteil` varchar(255) NOT NULL DEFAULT '',
  `kurzname` varchar(30) DEFAULT NULL,
  `user_login` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ;

alter table `mitarbeiter` add if not exists `user_login` varchar(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `zeiterfassung` (
  `id` varchar(36) NOT NULL,
  `job_id` varchar(36) NOT NULL,
  `mitarbeiter_id` varchar(36) NOT NULL,
  `task_date` date DEFAULT NULL,
  `task_start` datetime DEFAULT NULL,
  `task_end` datetime DEFAULT NULL,
  `gruppen_id` int(11) DEFAULT NULL,
  `hours` decimal(10,2) DEFAULT NULL,
  `remark` text DEFAULT NULL,
  `internal_hour_rate` decimal(10,2) DEFAULT NULL,
  `hour_rate` decimal(10,2) DEFAULT NULL,
  `state` int(11) DEFAULT 0,
  `create_date` datetime DEFAULT NULL,
  `update_date` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `login` varchar(255) DEFAULT NULL,
  `belegnummer` bigint(20) DEFAULT NULL,
  `submit_to_job` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_zeiterfassung_job_id` (`job_id`),
  KEY `fk_zeiterfassung_staff_link` (`mitarbeiter_id`),
  KEY `fk_zeiterfassung_gruppen_id` (`gruppen_id`),
  CONSTRAINT `fk_zeiterfassung_gruppen_id` FOREIGN KEY (`gruppen_id`) REFERENCES `artikelgruppen` (`gruppen_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_zeiterfassung_job_id` FOREIGN KEY (`job_id`) REFERENCES `tualo_job` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_zeiterfassung_staff_link` FOREIGN KEY (`mitarbeiter_id`) REFERENCES `mitarbeiter` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
);


SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `ds` (`allowform`,`autosave`,`base_store_class`,`class_name`,`combined`,`default_pagesize`,`displayfield`,`existsreal`,`globalsearch`,`listselectionmodel`,`listviewbaseclass`,`modelbaseclass`,`phpexporter`,`phpexporterfilename`,`searchany`,`searchfield`,`showactionbtn`,`sortdirection`,`sortfield`,`syncable`,`table_name`,`title`,`use_history`,`use_insert_for_update`) VALUES ('0','0','Tualo.DataSets.data.Store','ERP','0','1000','id','1','0','cellmodel','Tualo.DataSets.ListView','Tualo.DataSets.model.Basic','XlsxWriter','zeiterfassung {DATE} {TIME}','1','id','1','ASC','task_date','0','zeiterfassung','Zeiterfassung','0','0') ON DUPLICATE KEY UPDATE `allowform`=values(`allowform`),`autosave`=values(`autosave`),`base_store_class`=values(`base_store_class`),`class_name`=values(`class_name`),`combined`=values(`combined`),`default_pagesize`=values(`default_pagesize`),`displayfield`=values(`displayfield`),`existsreal`=values(`existsreal`),`globalsearch`=values(`globalsearch`),`listselectionmodel`=values(`listselectionmodel`),`listviewbaseclass`=values(`listviewbaseclass`),`modelbaseclass`=values(`modelbaseclass`),`phpexporter`=values(`phpexporter`),`phpexporterfilename`=values(`phpexporterfilename`),`searchany`=values(`searchany`),`searchfield`=values(`searchfield`),`showactionbtn`=values(`showactionbtn`),`sortdirection`=values(`sortdirection`),`sortfield`=values(`sortfield`),`syncable`=values(`syncable`),`table_name`=values(`table_name`),`title`=values(`title`),`use_history`=values(`use_history`),`use_insert_for_update`=values(`use_insert_for_update`); 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','belegnummer','bigint(20)','bigint','0','0','0','1','','NEVER','YES','0','19','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','create_date','datetime','datetime','0','0','{:now()}','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','MUL','gruppen_id','int(11)','int','0','0','0','1','','NEVER','YES','0','10','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','hours','decimal(10,2)','decimal','0','0','0','1','','NEVER','YES','0','10','2','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','hour_rate','decimal(10,2)','decimal','0','0','0','0','1','','NEVER','YES','0','10','2','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('36','utf8mb4','PRI','id','varchar(36)','varchar','0','0','{:uuid()}','0','1','','NEVER','NO','1','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','internal_hour_rate','decimal(10,2)','decimal','0','0','0','1','','NEVER','YES','0','10','2','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('36','utf8mb4','MUL','job_id','varchar(36)','varchar','0','0','0','1','','NEVER','NO','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('255','utf8mb4','','login','varchar(255)','varchar','0','0','{:getSessionUser()}','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('36','utf8mb4','MUL','mitarbeiter_id','varchar(36)','varchar','0','0','0','1','','NEVER','NO','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`character_set_name`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('65535','utf8mb4','','remark','text','text','0','0','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','MUL','staff_link','int(11)','int','0','0','','0','0','','NEVER','NO','0','10','0','select,insert,update,references','0','zeiterfassung','0') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','state','int(11)','int','0','0','0','0','1','','NEVER','YES','0','10','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','submit_to_job','bigint(20)','bigint','0','0','0','1','','NEVER','YES','0','19','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','task_date','date','date','0','0','{:curdate()}','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','task_end','datetime','datetime','0','0','{:now()}','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','task_start','datetime','datetime','0','0','{:now()}','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column` (`character_maximum_length`,`column_key`,`column_name`,`column_type`,`data_type`,`default_max_value`,`default_min_value`,`default_value`,`deferedload`,`existsreal`,`fieldtype`,`is_generated`,`is_nullable`,`is_primary`,`numeric_precision`,`numeric_scale`,`privileges`,`syncable`,`table_name`,`writeable`) VALUES ('0','','update_date','datetime','datetime','0','0','{:now()}','0','1','','NEVER','YES','0','0','0','select,insert,update,references','0','zeiterfassung','1') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('0','start','belegnummer','{}','','','1','','0','1','belegnummer','DE','','999','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','create_date','{}','','','1','','0','1','Anlage','DE','','12','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','gruppen_id','{}','','','1','','0','0','Leistung','DE','artikelgruppen_gruppen_id_listfilter','1','','','','zeiterfassung','column_artikelgruppen_gruppen_id') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','end','hours','{}','','','1','deValueRenderer','0','0','Stunden','DE','','3','','deValueRenderer','sum','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','hour_rate','{}','','','1','','0','1','Stundensatz (extern)','DE','','5','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','id','{}','','','1','','0','1','ID','DE','','10','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','internal_hour_rate','{}','','','1','','0','1','Stundensatz (intern)','DE','','4','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','job_id','{}','','','1','','0','1','Job','DE','','11','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','login','{}','','','1','','0','1','Login','DE','','14','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('0','start','mitarbeiter_id','{}','','','1','','0','1','mitarbeiter_id','DE','','999','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','remark','{}','','','1','','0','0','Bemerkung','DE','','2','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','staff_link','{}','','','1','','0','0','Mitarbeiter','DE','','7','','','','zeiterfassung','column_staff_urno') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','state','{}','','','1','','0','1','Status','DE','','6','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('0','start','submit_to_job','{}','','','1','','0','1','submit_to_job','DE','','999','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','task_date','{}','','','1','deDate','0','0','Datum','DE','','0','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','task_end','{}','','','1','','0','1','Ende','DE','','9','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','task_start','{}','','','1','','0','1','Beginn','DE','','8','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_list_label` (`active`,`align`,`column_name`,`config`,`editor`,`filterstore`,`flex`,`formatter`,`grouped`,`hidden`,`label`,`language`,`listfiltertype`,`position`,`renderer`,`summaryrenderer`,`summarytype`,`table_name`,`xtype`) VALUES ('1','left','update_date','{}','','','1','','0','1','Änderung','DE','','13','','','','zeiterfassung','gridcolumn') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','belegnummer','','Allgemein','1','1','belegnummer','DE','999','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','create_date','','Allgemein/Satzinformationen','1','1','Anlage','DE','12','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','gruppen_id','','Allgemein/Angaben','1','0','Leistung','DE','1','zeiterfassung','combobox_artikelgruppen_gruppe') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','hours','','Allgemein/Angaben','1','0','Stunden','DE','3','zeiterfassung','numberfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','hour_rate','','Allgemein/Angaben','1','0','Stundensatz (extern)','DE','5','zeiterfassung','numberfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','id','','Allgemein/Satzinformationen','1','1','ID','DE','10','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','internal_hour_rate','','Allgemein/Angaben','1','0','Stundensatz (intern)','DE','4','zeiterfassung','numberfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','job_id','','Allgemein/Satzinformationen','1','1','Job','DE','11','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','login','','Allgemein/Satzinformationen','1','1','Login','DE','14','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','mitarbeiter_id','','Allgemein','1','1','mitarbeiter_id','DE','999','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','remark','','Allgemein/Angaben','1','0','Bemerkung','DE','2','zeiterfassung','textarea') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','staff_link','','Allgemein/Angaben','1','0','Mitarbeiter','DE','7','zeiterfassung','combobox_staff_urno') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','state','','Allgemein/Angaben','1','0','Status','DE','6','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('0','0','submit_to_job','','Allgemein','1','1','submit_to_job','DE','999','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','task_date','','Allgemein/Angaben','1','0','Datum','DE','0','zeiterfassung','datefield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','task_end','','Allgemein/Angaben','1','1','Ende','DE','9','zeiterfassung','timefield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','task_start','','Allgemein/Angaben','1','1','Beginn','DE','8','zeiterfassung','timefield') ; 
INSERT IGNORE INTO `ds_column_form_label` (`active`,`allowempty`,`column_name`,`fieldgroup`,`field_path`,`flex`,`hidden`,`label`,`language`,`position`,`table_name`,`xtype`) VALUES ('1','0','update_date','','Allgemein/Satzinformationen','1','1','Änderung','DE','13','zeiterfassung','displayfield') ; 
INSERT IGNORE INTO `ds_reference_tables` (`active`,`autosync`,`columnsdef`,`constraint_name`,`existsreal`,`path`,`position`,`reference_table_name`,`searchable`,`table_name`,`tabtitle`) VALUES ('0','0','{\"gruppen_id\":\"gruppen_id\"}','fk_zeiterfassung_gruppen_id','1','','999','artikelgruppen','0','zeiterfassung','') ; 
INSERT IGNORE INTO `ds_reference_tables` (`active`,`autosync`,`columnsdef`,`constraint_name`,`existsreal`,`path`,`position`,`reference_table_name`,`searchable`,`table_name`,`tabtitle`) VALUES ('0','0','{\"staff_link\":\"urno\"}','fk_zeiterfassung_staff_link','1','','999','staff','0','zeiterfassung','') ; 
INSERT IGNORE INTO `ds_reference_tables` (`active`,`autosync`,`columnsdef`,`constraint_name`,`existsreal`,`path`,`position`,`reference_table_name`,`searchable`,`table_name`,`tabtitle`) VALUES ('0','0','{\"job_id\":\"id\"}','fk_zeiterfassung_job_id','1','','6','tualo_job','0','zeiterfassung','erfasste Zeiten') ; 
INSERT IGNORE INTO `ds_access` (`append`,`delete`,`read`,`role`,`table_name`,`write`) VALUES ('0','0','0','_default_','zeiterfassung','0') ; 
INSERT IGNORE INTO `ds_access` (`append`,`delete`,`read`,`role`,`table_name`,`write`) VALUES ('1','1','1','administration','zeiterfassung','1') ; 
REPLACE INTO `docsystem_ds` (`table_name`) VALUES ('zeiterfassung') ; 
SET FOREIGN_KEY_CHECKS=1;